spring.application.name=employee-tracking-backend

# ==========================
# DATABASE CONFIGURATION
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/employee_tracking_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=N_jangir@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / HIBERNATE CONFIGURATION
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# CORS CONFIGURATION
# ==========================
app.cors.allowed-origin=http://127.0.0.1:5500

# ==========================
# JWT CONFIGURATION
# ==========================
app.jwt.secret=SCAQTSfeEKH1uCh6QBptdwGIw9Dvqv0SuyORLzQxGX0=
app.jwt.expiration-ms=86400000

# ==========================
# ADMIN CREDENTIALS
# ==========================
app.admin.username=admin
app.admin.password=admin123

# ==========================
# LOGGING
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
